networks:
    1panel-network:
        external: true

services:
    tg-monitor:
        container_name: tg-monitor
        image: mrtangv/tg-monitor:latest
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
        environment:
            - TZ=Asia/Shanghai
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - "0.0.0.0:8080:8080"
        restart: always
        user: "0:0"
        volumes:
            - ./data:/app/data
